/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AuditorStakingInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "fundRewardPool" | "getRoleAdmin" | "grantRole" | "hasRole" | "minimumStakeThreshold" | "pauseContract" | "paused" | "payReward" | "pendingWithdrawAmount" | "renounceRole" | "requestUnstake" | "revokeRole" | "rewardPool" | "setMinimumStakeThreshold" | "slash" | "slasherRole" | "stake" | "stakeToken" | "stakedBalance" | "supportsInterface" | "unbondingPeriodSeconds" | "unbondingReleaseAt" | "unpauseContract" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MinimumStakeThresholdUpdated" | "Paused" | "RewardPoolFunded" | "Rewarded" | "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "Slashed" | "Staked" | "Unpaused" | "UnstakeRequested" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'fundRewardPool', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'minimumStakeThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'payReward', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'pendingWithdrawAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'requestUnstake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'rewardPool', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMinimumStakeThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'slash', values: [AddressLike, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'slasherRole', values?: undefined): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakeToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'stakedBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unbondingPeriodSeconds', values?: undefined): string;
encodeFunctionData(functionFragment: 'unbondingReleaseAt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpauseContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundRewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minimumStakeThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payReward', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingWithdrawAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestUnstake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinimumStakeThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slasherRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakedBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbondingPeriodSeconds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbondingReleaseAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace MinimumStakeThresholdUpdatedEvent {
      export type InputTuple = [previousThreshold: BigNumberish, newThreshold: BigNumberish];
      export type OutputTuple = [previousThreshold: bigint, newThreshold: bigint];
      export interface OutputObject {previousThreshold: bigint, newThreshold: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardPoolFundedEvent {
      export type InputTuple = [funder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [funder: string, amount: bigint];
      export interface OutputObject {funder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RewardedEvent {
      export type InputTuple = [auditor: AddressLike, amount: BigNumberish, reasonCode: string];
      export type OutputTuple = [auditor: string, amount: bigint, reasonCode: string];
      export interface OutputObject {auditor: string, amount: bigint, reasonCode: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SlashedEvent {
      export type InputTuple = [staker: AddressLike, amount: BigNumberish, reasonCode: string];
      export type OutputTuple = [staker: string, amount: bigint, reasonCode: string];
      export interface OutputObject {staker: string, amount: bigint, reasonCode: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StakedEvent {
      export type InputTuple = [staker: AddressLike, amount: BigNumberish, newBalance: BigNumberish];
      export type OutputTuple = [staker: string, amount: bigint, newBalance: bigint];
      export interface OutputObject {staker: string, amount: bigint, newBalance: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnstakeRequestedEvent {
      export type InputTuple = [staker: AddressLike, amount: BigNumberish];
      export type OutputTuple = [staker: string, amount: bigint];
      export interface OutputObject {staker: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [staker: AddressLike, amount: BigNumberish];
      export type OutputTuple = [staker: string, amount: bigint];
      export interface OutputObject {staker: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AuditorStaking extends BaseContract {
    
    connect(runner?: ContractRunner | null): AuditorStaking;
    waitForDeployment(): Promise<this>;

    interface: AuditorStakingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    fundRewardPool: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    minimumStakeThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pauseContract: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    payReward: TypedContractMethod<
      [auditor: AddressLike, amount: BigNumberish, reasonCode: string, ],
      [void],
      'nonpayable'
    >
    

    
    pendingWithdrawAmount: TypedContractMethod<
      [staker: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    requestUnstake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    rewardPool: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setMinimumStakeThreshold: TypedContractMethod<
      [newThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    slash: TypedContractMethod<
      [staker: AddressLike, amount: BigNumberish, reasonCode: string, ],
      [void],
      'nonpayable'
    >
    

    
    slasherRole: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakeToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stakedBalance: TypedContractMethod<
      [staker: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unbondingPeriodSeconds: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    unbondingReleaseAt: TypedContractMethod<
      [staker: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    unpauseContract: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fundRewardPool'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'minimumStakeThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pauseContract'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'payReward'): TypedContractMethod<
      [auditor: AddressLike, amount: BigNumberish, reasonCode: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pendingWithdrawAmount'): TypedContractMethod<
      [staker: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestUnstake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardPool'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setMinimumStakeThreshold'): TypedContractMethod<
      [newThreshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slash'): TypedContractMethod<
      [staker: AddressLike, amount: BigNumberish, reasonCode: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slasherRole'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakeToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stakedBalance'): TypedContractMethod<
      [staker: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unbondingPeriodSeconds'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unbondingReleaseAt'): TypedContractMethod<
      [staker: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unpauseContract'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MinimumStakeThresholdUpdated'): TypedContractEvent<MinimumStakeThresholdUpdatedEvent.InputTuple, MinimumStakeThresholdUpdatedEvent.OutputTuple, MinimumStakeThresholdUpdatedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RewardPoolFunded'): TypedContractEvent<RewardPoolFundedEvent.InputTuple, RewardPoolFundedEvent.OutputTuple, RewardPoolFundedEvent.OutputObject>;
getEvent(key: 'Rewarded'): TypedContractEvent<RewardedEvent.InputTuple, RewardedEvent.OutputTuple, RewardedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Slashed'): TypedContractEvent<SlashedEvent.InputTuple, SlashedEvent.OutputTuple, SlashedEvent.OutputObject>;
getEvent(key: 'Staked'): TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'UnstakeRequested'): TypedContractEvent<UnstakeRequestedEvent.InputTuple, UnstakeRequestedEvent.OutputTuple, UnstakeRequestedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'MinimumStakeThresholdUpdated(uint256,uint256)': TypedContractEvent<MinimumStakeThresholdUpdatedEvent.InputTuple, MinimumStakeThresholdUpdatedEvent.OutputTuple, MinimumStakeThresholdUpdatedEvent.OutputObject>;
      MinimumStakeThresholdUpdated: TypedContractEvent<MinimumStakeThresholdUpdatedEvent.InputTuple, MinimumStakeThresholdUpdatedEvent.OutputTuple, MinimumStakeThresholdUpdatedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RewardPoolFunded(address,uint256)': TypedContractEvent<RewardPoolFundedEvent.InputTuple, RewardPoolFundedEvent.OutputTuple, RewardPoolFundedEvent.OutputObject>;
      RewardPoolFunded: TypedContractEvent<RewardPoolFundedEvent.InputTuple, RewardPoolFundedEvent.OutputTuple, RewardPoolFundedEvent.OutputObject>;
    

      'Rewarded(address,uint256,string)': TypedContractEvent<RewardedEvent.InputTuple, RewardedEvent.OutputTuple, RewardedEvent.OutputObject>;
      Rewarded: TypedContractEvent<RewardedEvent.InputTuple, RewardedEvent.OutputTuple, RewardedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Slashed(address,uint256,string)': TypedContractEvent<SlashedEvent.InputTuple, SlashedEvent.OutputTuple, SlashedEvent.OutputObject>;
      Slashed: TypedContractEvent<SlashedEvent.InputTuple, SlashedEvent.OutputTuple, SlashedEvent.OutputObject>;
    

      'Staked(address,uint256,uint256)': TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
      Staked: TypedContractEvent<StakedEvent.InputTuple, StakedEvent.OutputTuple, StakedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'UnstakeRequested(address,uint256)': TypedContractEvent<UnstakeRequestedEvent.InputTuple, UnstakeRequestedEvent.OutputTuple, UnstakeRequestedEvent.OutputObject>;
      UnstakeRequested: TypedContractEvent<UnstakeRequestedEvent.InputTuple, UnstakeRequestedEvent.OutputTuple, UnstakeRequestedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }