/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"

export declare namespace CommitteeGovernance {

    export type SignatureStruct = {signer: AddressLike, nonce: BigNumberish, deadline: BigNumberish, signature: BytesLike}

    export type SignatureStructOutput = [signer: string, nonce: bigint, deadline: bigint, signature: string] & {signer: string, nonce: bigint, deadline: bigint, signature: string }


    export type SeatChangeProposalStruct = {oldSeat: AddressLike, effectiveAt: BigNumberish, expiresAt: BigNumberish, role: BigNumberish, executed: boolean, newSeat: AddressLike, proposedAtEpoch: BigNumberish}

    export type SeatChangeProposalStructOutput = [oldSeat: string, effectiveAt: bigint, expiresAt: bigint, role: bigint, executed: boolean, newSeat: string, proposedAtEpoch: bigint] & {oldSeat: string, effectiveAt: bigint, expiresAt: bigint, role: bigint, executed: boolean, newSeat: string, proposedAtEpoch: bigint }

    }

  export interface CommitteeGovernanceInterface extends Interface {
    getFunction(nameOrSignature: "bootstrapAdmin" | "bootstrapSeats" | "committeeEpoch" | "decisionRecorded" | "eip712Domain" | "executeSeatChange" | "getSeats" | "nonceBitmap" | "pauseSequence" | "paused" | "pausedUntil" | "proposeSeatChange" | "recordDecision" | "seatChangeProposalCount" | "seatChangeProposals" | "seatList" | "seatOf" | "seatsBootstrapped" | "setPaused"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DecisionRecorded" | "EIP712DomainChanged" | "GovernancePauseUpdated" | "SeatChangeExecuted" | "SeatChangeProposed" | "SeatsBootstrapped"): EventFragment;

    encodeFunctionData(functionFragment: 'bootstrapAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'bootstrapSeats', values: [[AddressLike, AddressLike, AddressLike, AddressLike, AddressLike], [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]]): string;
encodeFunctionData(functionFragment: 'committeeEpoch', values?: undefined): string;
encodeFunctionData(functionFragment: 'decisionRecorded', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'executeSeatChange', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSeats', values?: undefined): string;
encodeFunctionData(functionFragment: 'nonceBitmap', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseSequence', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pausedUntil', values?: undefined): string;
encodeFunctionData(functionFragment: 'proposeSeatChange', values: [AddressLike, AddressLike, BigNumberish, CommitteeGovernance.SignatureStruct[]]): string;
encodeFunctionData(functionFragment: 'recordDecision', values: [BigNumberish, BytesLike, boolean, BytesLike, CommitteeGovernance.SignatureStruct[]]): string;
encodeFunctionData(functionFragment: 'seatChangeProposalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'seatChangeProposals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'seatList', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'seatOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'seatsBootstrapped', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPaused', values: [boolean, CommitteeGovernance.SignatureStruct[]]): string;

    decodeFunctionResult(functionFragment: 'bootstrapAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bootstrapSeats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'committeeEpoch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decisionRecorded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executeSeatChange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSeats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonceBitmap', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseSequence', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pausedUntil', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proposeSeatChange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDecision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seatChangeProposalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seatChangeProposals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seatList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seatOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seatsBootstrapped', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPaused', data: BytesLike): Result;
  }


    export namespace DecisionRecordedEvent {
      export type InputTuple = [kind: BigNumberish, subjectId: BytesLike, approved: boolean, voters: AddressLike[], reasonHash: BytesLike];
      export type OutputTuple = [kind: bigint, subjectId: string, approved: boolean, voters: string[], reasonHash: string];
      export interface OutputObject {kind: bigint, subjectId: string, approved: boolean, voters: string[], reasonHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace GovernancePauseUpdatedEvent {
      export type InputTuple = [isPaused: boolean, pausedUntil: BigNumberish, pauseSequence: BigNumberish];
      export type OutputTuple = [isPaused: boolean, pausedUntil: bigint, pauseSequence: bigint];
      export interface OutputObject {isPaused: boolean, pausedUntil: bigint, pauseSequence: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace SeatChangeExecutedEvent {
      export type InputTuple = [proposalId: BigNumberish, oldSeat: AddressLike, newSeat: AddressLike];
      export type OutputTuple = [proposalId: bigint, oldSeat: string, newSeat: string];
      export interface OutputObject {proposalId: bigint, oldSeat: string, newSeat: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace SeatChangeProposedEvent {
      export type InputTuple = [proposalId: BigNumberish, oldSeat: AddressLike, newSeat: AddressLike, approvers: AddressLike[], effectiveAt: BigNumberish, expiresAt: BigNumberish, committeeEpoch: BigNumberish];
      export type OutputTuple = [proposalId: bigint, oldSeat: string, newSeat: string, approvers: string[], effectiveAt: bigint, expiresAt: bigint, committeeEpoch: bigint];
      export interface OutputObject {proposalId: bigint, oldSeat: string, newSeat: string, approvers: string[], effectiveAt: bigint, expiresAt: bigint, committeeEpoch: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace SeatsBootstrappedEvent {
      export type InputTuple = [seats: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike], roles: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]];
      export type OutputTuple = [seats: [string, string, string, string, string], roles: [bigint, bigint, bigint, bigint, bigint]];
      export interface OutputObject {seats: [string, string, string, string, string], roles: [bigint, bigint, bigint, bigint, bigint] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



  export interface CommitteeGovernance extends BaseContract {

    connect(runner?: ContractRunner | null): CommitteeGovernance;
    waitForDeployment(): Promise<this>;

    interface: CommitteeGovernanceInterface;


  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>




    bootstrapAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >



    bootstrapSeats: TypedContractMethod<
      [seats: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike], roles: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >



    committeeEpoch: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    decisionRecorded: TypedContractMethod<
      [decisionKey: BytesLike, ],
      [boolean],
      'view'
    >



    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >



    executeSeatChange: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >



    getSeats: TypedContractMethod<
      [],
      [[[string, string, string, string, string], [bigint, bigint, bigint, bigint, bigint]] & {seats: [string, string, string, string, string], roles: [bigint, bigint, bigint, bigint, bigint] }],
      'view'
    >



    nonceBitmap: TypedContractMethod<
      [signer: AddressLike, wordPosition: BigNumberish, ],
      [bigint],
      'view'
    >



    pauseSequence: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >



    pausedUntil: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    proposeSeatChange: TypedContractMethod<
      [oldSeat: AddressLike, newSeat: AddressLike, role: BigNumberish, signatures: CommitteeGovernance.SignatureStruct[], ],
      [bigint],
      'nonpayable'
    >



    recordDecision: TypedContractMethod<
      [kind: BigNumberish, subjectId: BytesLike, approved: boolean, reasonHash: BytesLike, signatures: CommitteeGovernance.SignatureStruct[], ],
      [void],
      'nonpayable'
    >



    seatChangeProposalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    seatChangeProposals: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [CommitteeGovernance.SeatChangeProposalStructOutput],
      'view'
    >



    seatList: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >



    seatOf: TypedContractMethod<
      [seat: AddressLike, ],
      [bigint],
      'view'
    >



    seatsBootstrapped: TypedContractMethod<
      [],
      [boolean],
      'view'
    >



    setPaused: TypedContractMethod<
      [shouldPause: boolean, signatures: CommitteeGovernance.SignatureStruct[], ],
      [void],
      'nonpayable'
    >



    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'bootstrapAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'bootstrapSeats'): TypedContractMethod<
      [seats: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike], roles: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'committeeEpoch'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'decisionRecorded'): TypedContractMethod<
      [decisionKey: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'executeSeatChange'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getSeats'): TypedContractMethod<
      [],
      [[[string, string, string, string, string], [bigint, bigint, bigint, bigint, bigint]] & {seats: [string, string, string, string, string], roles: [bigint, bigint, bigint, bigint, bigint] }],
      'view'
    >;
getFunction(nameOrSignature: 'nonceBitmap'): TypedContractMethod<
      [signer: AddressLike, wordPosition: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pauseSequence'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pausedUntil'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proposeSeatChange'): TypedContractMethod<
      [oldSeat: AddressLike, newSeat: AddressLike, role: BigNumberish, signatures: CommitteeGovernance.SignatureStruct[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordDecision'): TypedContractMethod<
      [kind: BigNumberish, subjectId: BytesLike, approved: boolean, reasonHash: BytesLike, signatures: CommitteeGovernance.SignatureStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seatChangeProposalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'seatChangeProposals'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [CommitteeGovernance.SeatChangeProposalStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'seatList'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'seatOf'): TypedContractMethod<
      [seat: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'seatsBootstrapped'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setPaused'): TypedContractMethod<
      [shouldPause: boolean, signatures: CommitteeGovernance.SignatureStruct[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DecisionRecorded'): TypedContractEvent<DecisionRecordedEvent.InputTuple, DecisionRecordedEvent.OutputTuple, DecisionRecordedEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'GovernancePauseUpdated'): TypedContractEvent<GovernancePauseUpdatedEvent.InputTuple, GovernancePauseUpdatedEvent.OutputTuple, GovernancePauseUpdatedEvent.OutputObject>;
getEvent(key: 'SeatChangeExecuted'): TypedContractEvent<SeatChangeExecutedEvent.InputTuple, SeatChangeExecutedEvent.OutputTuple, SeatChangeExecutedEvent.OutputObject>;
getEvent(key: 'SeatChangeProposed'): TypedContractEvent<SeatChangeProposedEvent.InputTuple, SeatChangeProposedEvent.OutputTuple, SeatChangeProposedEvent.OutputObject>;
getEvent(key: 'SeatsBootstrapped'): TypedContractEvent<SeatsBootstrappedEvent.InputTuple, SeatsBootstrappedEvent.OutputTuple, SeatsBootstrappedEvent.OutputObject>;

    filters: {

      'DecisionRecorded(uint8,bytes32,bool,address[],bytes32)': TypedContractEvent<DecisionRecordedEvent.InputTuple, DecisionRecordedEvent.OutputTuple, DecisionRecordedEvent.OutputObject>;
      DecisionRecorded: TypedContractEvent<DecisionRecordedEvent.InputTuple, DecisionRecordedEvent.OutputTuple, DecisionRecordedEvent.OutputObject>;


      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;


      'GovernancePauseUpdated(bool,uint40,uint64)': TypedContractEvent<GovernancePauseUpdatedEvent.InputTuple, GovernancePauseUpdatedEvent.OutputTuple, GovernancePauseUpdatedEvent.OutputObject>;
      GovernancePauseUpdated: TypedContractEvent<GovernancePauseUpdatedEvent.InputTuple, GovernancePauseUpdatedEvent.OutputTuple, GovernancePauseUpdatedEvent.OutputObject>;


      'SeatChangeExecuted(uint256,address,address)': TypedContractEvent<SeatChangeExecutedEvent.InputTuple, SeatChangeExecutedEvent.OutputTuple, SeatChangeExecutedEvent.OutputObject>;
      SeatChangeExecuted: TypedContractEvent<SeatChangeExecutedEvent.InputTuple, SeatChangeExecutedEvent.OutputTuple, SeatChangeExecutedEvent.OutputObject>;


      'SeatChangeProposed(uint256,address,address,address[],uint256,uint256,uint64)': TypedContractEvent<SeatChangeProposedEvent.InputTuple, SeatChangeProposedEvent.OutputTuple, SeatChangeProposedEvent.OutputObject>;
      SeatChangeProposed: TypedContractEvent<SeatChangeProposedEvent.InputTuple, SeatChangeProposedEvent.OutputTuple, SeatChangeProposedEvent.OutputObject>;


      'SeatsBootstrapped(address[5],uint8[5])': TypedContractEvent<SeatsBootstrappedEvent.InputTuple, SeatsBootstrappedEvent.OutputTuple, SeatsBootstrappedEvent.OutputObject>;
      SeatsBootstrapped: TypedContractEvent<SeatsBootstrappedEvent.InputTuple, SeatsBootstrappedEvent.OutputTuple, SeatsBootstrappedEvent.OutputObject>;

    };
  }