/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace DcpDonationRanking {
      
    export type ProjectSnapshotStruct = {exists: boolean, projectStatus: BigNumberish, totalDonationAmount: BigNumberish, donorCount: BigNumberish, donationTransactionCount: BigNumberish}

    export type ProjectSnapshotStructOutput = [exists: boolean, projectStatus: bigint, totalDonationAmount: bigint, donorCount: bigint, donationTransactionCount: bigint] & {exists: boolean, projectStatus: bigint, totalDonationAmount: bigint, donorCount: bigint, donationTransactionCount: bigint }
  
    }

  export interface DcpDonationRankingInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_ADMIN_ROLE" | "charityToken" | "createProject" | "donate" | "getProjectSnapshot" | "getRoleAdmin" | "grantProjectManagerRole" | "grantRole" | "hasDonatedToProject" | "hasRole" | "pauseContract" | "paused" | "projectManagerRole" | "renounceRole" | "revokeProjectManagerRole" | "revokeRole" | "setProjectStatus" | "supportsInterface" | "unpauseContract"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DonationReceived" | "Paused" | "ProjectCreated" | "ProjectStatusUpdated" | "RoleAdminChanged" | "RoleGranted" | "RolePermissionUpdated" | "RoleRevoked" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'charityToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'createProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'donate', values: [BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'getProjectSnapshot', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantProjectManagerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasDonatedToProject', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'pauseContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'projectManagerRole', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeProjectManagerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'setProjectStatus', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpauseContract', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'charityToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProjectSnapshot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantProjectManagerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasDonatedToProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectManagerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeProjectManagerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setProjectStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseContract', data: BytesLike): Result;
  }

  
    export namespace DonationReceivedEvent {
      export type InputTuple = [donor: AddressLike, projectId: BigNumberish, amount: BigNumberish, timestamp: BigNumberish, isAnonymous: boolean];
      export type OutputTuple = [donor: string, projectId: bigint, amount: bigint, timestamp: bigint, isAnonymous: boolean];
      export interface OutputObject {donor: string, projectId: bigint, amount: bigint, timestamp: bigint, isAnonymous: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [projectId: BigNumberish, projectStatus: BigNumberish];
      export type OutputTuple = [projectId: bigint, projectStatus: bigint];
      export interface OutputObject {projectId: bigint, projectStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectStatusUpdatedEvent {
      export type InputTuple = [projectId: BigNumberish, previousStatus: BigNumberish, newStatus: BigNumberish];
      export type OutputTuple = [projectId: bigint, previousStatus: bigint, newStatus: bigint];
      export interface OutputObject {projectId: bigint, previousStatus: bigint, newStatus: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RolePermissionUpdatedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, isGranted: boolean];
      export type OutputTuple = [role: string, account: string, isGranted: boolean];
      export interface OutputObject {role: string, account: string, isGranted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DcpDonationRanking extends BaseContract {
    
    connect(runner?: ContractRunner | null): DcpDonationRanking;
    waitForDeployment(): Promise<this>;

    interface: DcpDonationRankingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    charityToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    donate: TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, isAnonymous: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    getProjectSnapshot: TypedContractMethod<
      [projectId: BigNumberish, ],
      [DcpDonationRanking.ProjectSnapshotStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    grantProjectManagerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasDonatedToProject: TypedContractMethod<
      [projectId: BigNumberish, donorAddress: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pauseContract: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    projectManagerRole: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeProjectManagerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setProjectStatus: TypedContractMethod<
      [projectId: BigNumberish, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpauseContract: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'charityToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'donate'): TypedContractMethod<
      [projectId: BigNumberish, amount: BigNumberish, isAnonymous: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getProjectSnapshot'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [DcpDonationRanking.ProjectSnapshotStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'grantProjectManagerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasDonatedToProject'): TypedContractMethod<
      [projectId: BigNumberish, donorAddress: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pauseContract'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'projectManagerRole'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeProjectManagerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setProjectStatus'): TypedContractMethod<
      [projectId: BigNumberish, newStatus: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpauseContract'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DonationReceived'): TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
getEvent(key: 'ProjectStatusUpdated'): TypedContractEvent<ProjectStatusUpdatedEvent.InputTuple, ProjectStatusUpdatedEvent.OutputTuple, ProjectStatusUpdatedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RolePermissionUpdated'): TypedContractEvent<RolePermissionUpdatedEvent.InputTuple, RolePermissionUpdatedEvent.OutputTuple, RolePermissionUpdatedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'DonationReceived(address,uint256,uint256,uint256,bool)': TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
      DonationReceived: TypedContractEvent<DonationReceivedEvent.InputTuple, DonationReceivedEvent.OutputTuple, DonationReceivedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProjectCreated(uint256,uint8)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    

      'ProjectStatusUpdated(uint256,uint8,uint8)': TypedContractEvent<ProjectStatusUpdatedEvent.InputTuple, ProjectStatusUpdatedEvent.OutputTuple, ProjectStatusUpdatedEvent.OutputObject>;
      ProjectStatusUpdated: TypedContractEvent<ProjectStatusUpdatedEvent.InputTuple, ProjectStatusUpdatedEvent.OutputTuple, ProjectStatusUpdatedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RolePermissionUpdated(bytes32,address,bool)': TypedContractEvent<RolePermissionUpdatedEvent.InputTuple, RolePermissionUpdatedEvent.OutputTuple, RolePermissionUpdatedEvent.OutputObject>;
      RolePermissionUpdated: TypedContractEvent<RolePermissionUpdatedEvent.InputTuple, RolePermissionUpdatedEvent.OutputTuple, RolePermissionUpdatedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }