/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IImpactSBTInterface extends Interface {
    getFunction(nameOrSignature: "getTokenMetadata" | "getTokenStatus" | "isOracle" | "locked" | "mint" | "pause" | "tokenURI" | "totalSupply" | "transferOracleRole" | "unpause" | "updateTokenStatus"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getTokenMetadata', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTokenStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isOracle', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'locked', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'mint', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, string, string, string]): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenURI', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOracleRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateTokenStatus', values: [BigNumberish, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'getTokenMetadata', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'locked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOracleRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenStatus', data: BytesLike): Result;
  }

  

  export interface IImpactSBT extends BaseContract {
    
    connect(runner?: ContractRunner | null): IImpactSBT;
    waitForDeployment(): Promise<this>;

    interface: IImpactSBTInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getTokenMetadata: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, bigint] & {projectId: bigint, milestone: bigint, beneficiaryCount: bigint, gpsCoordinates: string, imageCID: string, mintedAt: bigint }],
      'view'
    >
    

    
    getTokenStatus: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    isOracle: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    locked: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [to: AddressLike, projectId: BigNumberish, milestone: BigNumberish, beneficiaryCount: BigNumberish, gpsCoordinates: string, imageCID: string, tokenURI_: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    tokenURI: TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOracleRole: TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateTokenStatus: TypedContractMethod<
      [tokenId: BigNumberish, newStatus: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getTokenMetadata'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [[bigint, bigint, bigint, string, string, bigint] & {projectId: bigint, milestone: bigint, beneficiaryCount: bigint, gpsCoordinates: string, imageCID: string, mintedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenStatus'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isOracle'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'locked'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [to: AddressLike, projectId: BigNumberish, milestone: BigNumberish, beneficiaryCount: BigNumberish, gpsCoordinates: string, imageCID: string, tokenURI_: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenURI'): TypedContractMethod<
      [tokenId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOracleRole'): TypedContractMethod<
      [newOracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenStatus'): TypedContractMethod<
      [tokenId: BigNumberish, newStatus: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }