/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace MultisigDisbursement {
      
    export type RequestDataStruct = {exists: boolean, requestId: BigNumberish, projectId: BigNumberish, beneficiaryAddress: AddressLike, amount: BigNumberish, status: BigNumberish, approvalCount: BigNumberish, signedCount: BigNumberish, createdAt: BigNumberish, executedAt: BigNumberish, cancelledAt: BigNumberish, adminSigned: boolean, orgSigned: boolean, regulatorySigned: boolean, timeoutDeadline: BigNumberish, maxWithdrawable: BigNumberish, requestMode: BigNumberish, requiredApprovals: BigNumberish, raisedRatioBpsAtCreation: BigNumberish, adminRoleSignatureCollected: boolean, orgRoleSignatureCollected: boolean, regulatoryRoleSignatureCollected: boolean}

    export type RequestDataStructOutput = [exists: boolean, requestId: bigint, projectId: bigint, beneficiaryAddress: string, amount: bigint, status: bigint, approvalCount: bigint, signedCount: bigint, createdAt: bigint, executedAt: bigint, cancelledAt: bigint, adminSigned: boolean, orgSigned: boolean, regulatorySigned: boolean, timeoutDeadline: bigint, maxWithdrawable: bigint, requestMode: bigint, requiredApprovals: bigint, raisedRatioBpsAtCreation: bigint, adminRoleSignatureCollected: boolean, orgRoleSignatureCollected: boolean, regulatoryRoleSignatureCollected: boolean] & {exists: boolean, requestId: bigint, projectId: bigint, beneficiaryAddress: string, amount: bigint, status: bigint, approvalCount: bigint, signedCount: bigint, createdAt: bigint, executedAt: bigint, cancelledAt: bigint, adminSigned: boolean, orgSigned: boolean, regulatorySigned: boolean, timeoutDeadline: bigint, maxWithdrawable: bigint, requestMode: bigint, requiredApprovals: bigint, raisedRatioBpsAtCreation: bigint, adminRoleSignatureCollected: boolean, orgRoleSignatureCollected: boolean, regulatoryRoleSignatureCollected: boolean }
  

    export type RequestStringsStruct = {evidenceCid: string, rejectReason: string}

    export type RequestStringsStructOutput = [evidenceCid: string, rejectReason: string] & {evidenceCid: string, rejectReason: string }
  
    }

  export interface MultisigDisbursementInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_SIGNER_ROLE" | "APPROVALS_THREE_OF_THREE" | "APPROVALS_TWO_OF_THREE" | "BASIS_POINTS_DENOMINATOR" | "DEFAULT_ADMIN_ROLE" | "FAST_TRACK_RAISED_BPS" | "MIN_NORMAL_RAISED_BPS" | "MIN_SIGNERS_PER_ROLE" | "ORG_SIGNER_ROLE" | "REGULATORY_SIGNER_ROLE" | "TIMEOUT_SECONDS" | "WITHDRAWAL_RESERVE_BPS" | "cancelRequestByAdmin" | "charityToken" | "createDisbursementRequest" | "donationRanking" | "extendRequestTimeout" | "finalizeDisbursement" | "getMaxWithdrawableAmount" | "getRequest" | "getRequestStrings" | "getRoleAdmin" | "getRoleSignerCount" | "grantAdminSignerRole" | "grantOrgSignerRole" | "grantRegulatorySignerRole" | "grantRole" | "hasRole" | "hasSigned" | "isRequestExpired" | "pauseContract" | "paused" | "rejectRequest" | "renounceRole" | "revokeAdminSignerRole" | "revokeOrgSignerRole" | "revokeRegulatorySignerRole" | "revokeRole" | "signRequest" | "supportsInterface" | "unpauseContract"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisbursementExecuted" | "Paused" | "RequestCreated" | "RequestSigned" | "RequestStatusChanged" | "RequestTimeoutExtended" | "RoleAdminChanged" | "RoleGranted" | "RolePermissionUpdated" | "RoleRevoked" | "ThresholdSignaturesReached" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_SIGNER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'APPROVALS_THREE_OF_THREE', values?: undefined): string;
encodeFunctionData(functionFragment: 'APPROVALS_TWO_OF_THREE', values?: undefined): string;
encodeFunctionData(functionFragment: 'BASIS_POINTS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'FAST_TRACK_RAISED_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_NORMAL_RAISED_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_SIGNERS_PER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'ORG_SIGNER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'REGULATORY_SIGNER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIMEOUT_SECONDS', values?: undefined): string;
encodeFunctionData(functionFragment: 'WITHDRAWAL_RESERVE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelRequestByAdmin', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'charityToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'createDisbursementRequest', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'donationRanking', values?: undefined): string;
encodeFunctionData(functionFragment: 'extendRequestTimeout', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'finalizeDisbursement', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMaxWithdrawableAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRequestStrings', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRoleSignerCount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'grantAdminSignerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantOrgSignerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRegulatorySignerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasSigned', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isRequestExpired', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectRequest', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeAdminSignerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeOrgSignerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRegulatorySignerRole', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'signRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'unpauseContract', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ADMIN_SIGNER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'APPROVALS_THREE_OF_THREE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'APPROVALS_TWO_OF_THREE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BASIS_POINTS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FAST_TRACK_RAISED_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_NORMAL_RAISED_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_SIGNERS_PER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ORG_SIGNER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'REGULATORY_SIGNER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIMEOUT_SECONDS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WITHDRAWAL_RESERVE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelRequestByAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'charityToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDisbursementRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donationRanking', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'extendRequestTimeout', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeDisbursement', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMaxWithdrawableAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRequestStrings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleSignerCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAdminSignerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantOrgSignerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRegulatorySignerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasSigned', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRequestExpired', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeAdminSignerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeOrgSignerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRegulatorySignerRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseContract', data: BytesLike): Result;
  }

  
    export namespace DisbursementExecutedEvent {
      export type InputTuple = [requestId: BigNumberish, projectId: BigNumberish, amount: BigNumberish, beneficiary: AddressLike, transactionId: BigNumberish, burnedAt: BigNumberish];
      export type OutputTuple = [requestId: bigint, projectId: bigint, amount: bigint, beneficiary: string, transactionId: bigint, burnedAt: bigint];
      export interface OutputObject {requestId: bigint, projectId: bigint, amount: bigint, beneficiary: string, transactionId: bigint, burnedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestCreatedEvent {
      export type InputTuple = [requestId: BigNumberish, projectId: BigNumberish, beneficiary: AddressLike, amount: BigNumberish, evidenceCid: string, createdAt: BigNumberish, timeoutDeadline: BigNumberish, requestMode: BigNumberish, requiredApprovals: BigNumberish, raisedRatioBpsAtCreation: BigNumberish];
      export type OutputTuple = [requestId: bigint, projectId: bigint, beneficiary: string, amount: bigint, evidenceCid: string, createdAt: bigint, timeoutDeadline: bigint, requestMode: bigint, requiredApprovals: bigint, raisedRatioBpsAtCreation: bigint];
      export interface OutputObject {requestId: bigint, projectId: bigint, beneficiary: string, amount: bigint, evidenceCid: string, createdAt: bigint, timeoutDeadline: bigint, requestMode: bigint, requiredApprovals: bigint, raisedRatioBpsAtCreation: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestSignedEvent {
      export type InputTuple = [requestId: BigNumberish, signer: AddressLike, signerRole: BytesLike];
      export type OutputTuple = [requestId: bigint, signer: string, signerRole: string];
      export interface OutputObject {requestId: bigint, signer: string, signerRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestStatusChangedEvent {
      export type InputTuple = [requestId: BigNumberish, previousStatus: BigNumberish, newStatus: BigNumberish, reason: string];
      export type OutputTuple = [requestId: bigint, previousStatus: bigint, newStatus: bigint, reason: string];
      export interface OutputObject {requestId: bigint, previousStatus: bigint, newStatus: bigint, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RequestTimeoutExtendedEvent {
      export type InputTuple = [requestId: BigNumberish, newTimeoutDeadline: BigNumberish, extendedBy: AddressLike];
      export type OutputTuple = [requestId: bigint, newTimeoutDeadline: bigint, extendedBy: string];
      export interface OutputObject {requestId: bigint, newTimeoutDeadline: bigint, extendedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RolePermissionUpdatedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, isGranted: boolean];
      export type OutputTuple = [role: string, account: string, isGranted: boolean];
      export interface OutputObject {role: string, account: string, isGranted: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ThresholdSignaturesReachedEvent {
      export type InputTuple = [requestId: BigNumberish, projectId: BigNumberish, amount: BigNumberish, beneficiary: AddressLike, reachedAt: BigNumberish];
      export type OutputTuple = [requestId: bigint, projectId: bigint, amount: bigint, beneficiary: string, reachedAt: bigint];
      export interface OutputObject {requestId: bigint, projectId: bigint, amount: bigint, beneficiary: string, reachedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MultisigDisbursement extends BaseContract {
    
    connect(runner?: ContractRunner | null): MultisigDisbursement;
    waitForDeployment(): Promise<this>;

    interface: MultisigDisbursementInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_SIGNER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    APPROVALS_THREE_OF_THREE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    APPROVALS_TWO_OF_THREE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BASIS_POINTS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    FAST_TRACK_RAISED_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_NORMAL_RAISED_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_SIGNERS_PER_ROLE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ORG_SIGNER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    REGULATORY_SIGNER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    TIMEOUT_SECONDS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WITHDRAWAL_RESERVE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelRequestByAdmin: TypedContractMethod<
      [requestId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    charityToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createDisbursementRequest: TypedContractMethod<
      [projectId: BigNumberish, beneficiary: AddressLike, amount: BigNumberish, projectGoalAmount: BigNumberish, evidenceCid: string, requestMode: BigNumberish, emergencyReason: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    donationRanking: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    extendRequestTimeout: TypedContractMethod<
      [requestId: BigNumberish, additionalSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeDisbursement: TypedContractMethod<
      [requestId: BigNumberish, transactionId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getMaxWithdrawableAmount: TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [MultisigDisbursement.RequestDataStructOutput],
      'view'
    >
    

    
    getRequestStrings: TypedContractMethod<
      [requestId: BigNumberish, ],
      [MultisigDisbursement.RequestStringsStructOutput],
      'view'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getRoleSignerCount: TypedContractMethod<
      [role: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    grantAdminSignerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantOrgSignerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRegulatorySignerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    hasSigned: TypedContractMethod<
      [requestId: BigNumberish, signer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRequestExpired: TypedContractMethod<
      [requestId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    pauseContract: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    rejectRequest: TypedContractMethod<
      [requestId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeAdminSignerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeOrgSignerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRegulatorySignerRole: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    signRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    unpauseContract: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_SIGNER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'APPROVALS_THREE_OF_THREE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'APPROVALS_TWO_OF_THREE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BASIS_POINTS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'FAST_TRACK_RAISED_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_NORMAL_RAISED_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_SIGNERS_PER_ROLE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ORG_SIGNER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'REGULATORY_SIGNER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'TIMEOUT_SECONDS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WITHDRAWAL_RESERVE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelRequestByAdmin'): TypedContractMethod<
      [requestId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'charityToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createDisbursementRequest'): TypedContractMethod<
      [projectId: BigNumberish, beneficiary: AddressLike, amount: BigNumberish, projectGoalAmount: BigNumberish, evidenceCid: string, requestMode: BigNumberish, emergencyReason: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'donationRanking'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'extendRequestTimeout'): TypedContractMethod<
      [requestId: BigNumberish, additionalSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeDisbursement'): TypedContractMethod<
      [requestId: BigNumberish, transactionId: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getMaxWithdrawableAmount'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [MultisigDisbursement.RequestDataStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRequestStrings'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [MultisigDisbursement.RequestStringsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRoleSignerCount'): TypedContractMethod<
      [role: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantAdminSignerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantOrgSignerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRegulatorySignerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'hasSigned'): TypedContractMethod<
      [requestId: BigNumberish, signer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRequestExpired'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pauseContract'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rejectRequest'): TypedContractMethod<
      [requestId: BigNumberish, reason: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeAdminSignerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeOrgSignerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRegulatorySignerRole'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'unpauseContract'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DisbursementExecuted'): TypedContractEvent<DisbursementExecutedEvent.InputTuple, DisbursementExecutedEvent.OutputTuple, DisbursementExecutedEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RequestCreated'): TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
getEvent(key: 'RequestSigned'): TypedContractEvent<RequestSignedEvent.InputTuple, RequestSignedEvent.OutputTuple, RequestSignedEvent.OutputObject>;
getEvent(key: 'RequestStatusChanged'): TypedContractEvent<RequestStatusChangedEvent.InputTuple, RequestStatusChangedEvent.OutputTuple, RequestStatusChangedEvent.OutputObject>;
getEvent(key: 'RequestTimeoutExtended'): TypedContractEvent<RequestTimeoutExtendedEvent.InputTuple, RequestTimeoutExtendedEvent.OutputTuple, RequestTimeoutExtendedEvent.OutputObject>;
getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RolePermissionUpdated'): TypedContractEvent<RolePermissionUpdatedEvent.InputTuple, RolePermissionUpdatedEvent.OutputTuple, RolePermissionUpdatedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'ThresholdSignaturesReached'): TypedContractEvent<ThresholdSignaturesReachedEvent.InputTuple, ThresholdSignaturesReachedEvent.OutputTuple, ThresholdSignaturesReachedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'DisbursementExecuted(uint256,uint256,uint256,address,uint256,uint256)': TypedContractEvent<DisbursementExecutedEvent.InputTuple, DisbursementExecutedEvent.OutputTuple, DisbursementExecutedEvent.OutputObject>;
      DisbursementExecuted: TypedContractEvent<DisbursementExecutedEvent.InputTuple, DisbursementExecutedEvent.OutputTuple, DisbursementExecutedEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RequestCreated(uint256,uint256,address,uint256,string,uint256,uint256,uint8,uint256,uint256)': TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
      RequestCreated: TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
    

      'RequestSigned(uint256,address,bytes32)': TypedContractEvent<RequestSignedEvent.InputTuple, RequestSignedEvent.OutputTuple, RequestSignedEvent.OutputObject>;
      RequestSigned: TypedContractEvent<RequestSignedEvent.InputTuple, RequestSignedEvent.OutputTuple, RequestSignedEvent.OutputObject>;
    

      'RequestStatusChanged(uint256,uint8,uint8,string)': TypedContractEvent<RequestStatusChangedEvent.InputTuple, RequestStatusChangedEvent.OutputTuple, RequestStatusChangedEvent.OutputObject>;
      RequestStatusChanged: TypedContractEvent<RequestStatusChangedEvent.InputTuple, RequestStatusChangedEvent.OutputTuple, RequestStatusChangedEvent.OutputObject>;
    

      'RequestTimeoutExtended(uint256,uint256,address)': TypedContractEvent<RequestTimeoutExtendedEvent.InputTuple, RequestTimeoutExtendedEvent.OutputTuple, RequestTimeoutExtendedEvent.OutputObject>;
      RequestTimeoutExtended: TypedContractEvent<RequestTimeoutExtendedEvent.InputTuple, RequestTimeoutExtendedEvent.OutputTuple, RequestTimeoutExtendedEvent.OutputObject>;
    

      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RolePermissionUpdated(bytes32,address,bool)': TypedContractEvent<RolePermissionUpdatedEvent.InputTuple, RolePermissionUpdatedEvent.OutputTuple, RolePermissionUpdatedEvent.OutputObject>;
      RolePermissionUpdated: TypedContractEvent<RolePermissionUpdatedEvent.InputTuple, RolePermissionUpdatedEvent.OutputTuple, RolePermissionUpdatedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'ThresholdSignaturesReached(uint256,uint256,uint256,address,uint256)': TypedContractEvent<ThresholdSignaturesReachedEvent.InputTuple, ThresholdSignaturesReachedEvent.OutputTuple, ThresholdSignaturesReachedEvent.OutputObject>;
      ThresholdSignaturesReached: TypedContractEvent<ThresholdSignaturesReachedEvent.InputTuple, ThresholdSignaturesReachedEvent.OutputTuple, ThresholdSignaturesReachedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }