/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IERC5192, IERC5192Interface } from "../../ImpactSBT.sol/IERC5192.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "locked",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IERC5192__factory {
    static readonly abi = _abi;
    static createInterface(): IERC5192Interface {
      return new Interface(_abi) as IERC5192Interface;
    }
    static connect(address: string, runner?: ContractRunner | null): IERC5192 {
      return new Contract(address, _abi, runner) as unknown as IERC5192;
    }
  }
  